title: Namestead
description: Asset workflow and quality toolkit for the Unreal Engine editor
url: https://lowszehao.github.io
baseurl: /namestead-docs

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 2..3

exclude:
  - README.md
